# Allow replication connections from any host in the Docker network
host    all             all             0.0.0.0/0               md5
host    replication     all             0.0.0.0/0               md5
